/**
 * withAndroidWidget.js — Expo Config Plugin
 *
 * Injects the TibiaOT home-screen widget into the Android native project
 * generated by `expo prebuild`.  All source files live under mobile/plugins/
 * so they survive the `--clean` flag used in build-android.sh.
 *
 * What this plugin does:
 *  1. Copies Java sources  → android/app/src/main/java/com/tibiaotmonitor/widget/
 *  2. Copies XML resources → android/app/src/main/res/{layout,xml,drawable}/
 *  3. Registers the AppWidgetProvider receiver in AndroidManifest.xml
 *  4. Registers TibiaPrefsPackage in MainApplication.kt (or .java)
 */

const {
  withAndroidManifest,
  withMainApplication,
  withDangerousMod,
} = require('@expo/config-plugins');
const path = require('path');
const fs   = require('fs');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function copyFile(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

// ---------------------------------------------------------------------------
// Step 1 – copy files into the generated android/ directory
// ---------------------------------------------------------------------------

function withWidgetFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot; // …/mobile/android
      const pluginsDir  = path.join(cfg.modRequest.projectRoot, 'plugins');

      // Java sources
      const javaDest = path.join(
        androidRoot,
        'app/src/main/java/com/tibiaotmonitor/widget',
      );
      for (const file of [
        'TibiaWidgetProvider.java',
        'TibiaPrefsModule.java',
        'TibiaPrefsPackage.java',
      ]) {
        copyFile(
          path.join(pluginsDir, 'java', file),
          path.join(javaDest, file),
        );
      }

      // XML resources
      copyFile(
        path.join(pluginsDir, 'res/layout/tibia_widget_layout.xml'),
        path.join(androidRoot, 'app/src/main/res/layout/tibia_widget_layout.xml'),
      );
      copyFile(
        path.join(pluginsDir, 'res/xml/tibia_widget_info.xml'),
        path.join(androidRoot, 'app/src/main/res/xml/tibia_widget_info.xml'),
      );
      copyFile(
        path.join(pluginsDir, 'res/drawable/widget_bg.xml'),
        path.join(androidRoot, 'app/src/main/res/drawable/widget_bg.xml'),
      );

      return cfg;
    },
  ]);
}

// ---------------------------------------------------------------------------
// Step 2 – register the AppWidgetProvider receiver in AndroidManifest.xml
// ---------------------------------------------------------------------------

function withWidgetManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application[0];

    if (!application.receiver) application.receiver = [];

    // Avoid duplicate entries on repeated prebuild runs
    const alreadyRegistered = application.receiver.some(
      (r) =>
        r.$['android:name'] === 'com.tibiaotmonitor.widget.TibiaWidgetProvider',
    );
    if (alreadyRegistered) return cfg;

    application.receiver.push({
      $: {
        'android:name':     'com.tibiaotmonitor.widget.TibiaWidgetProvider',
        'android:exported': 'true',
      },
      'intent-filter': [
        {
          action: [
            {
              $: {
                'android:name':
                  'android.appwidget.action.APPWIDGET_UPDATE',
              },
            },
          ],
        },
      ],
      'meta-data': [
        {
          $: {
            'android:name':     'android.appwidget.provider',
            'android:resource': '@xml/tibia_widget_info',
          },
        },
      ],
    });

    return cfg;
  });
}

// ---------------------------------------------------------------------------
// Step 3 – register TibiaPrefsPackage in MainApplication
// ---------------------------------------------------------------------------

function withWidgetMainApplication(config) {
  return withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;

    const isKotlin = cfg.modResults.language === 'kt';

    const importLine = 'import com.tibiaotmonitor.widget.TibiaPrefsPackage';

    // --- insert import ---
    if (!src.includes(importLine)) {
      // Anchor on the PackageList import which is always present in the
      // Expo-generated MainApplication (both .kt and .java)
      src = src.replace(
        /(import com\.facebook\.react\.PackageList)/,
        `${importLine}\n$1`,
      );
    }

    // --- register package ---
    if (!src.includes('TibiaPrefsPackage()')) {
      if (isKotlin) {
        // Expo 51 / RN 0.74 Kotlin template:
        //   PackageList(this).packages.apply {
        //     // add(MyPackage())
        //   }
        src = src.replace(
          /PackageList\(this\)\.packages\.apply \{/,
          'PackageList(this).packages.apply {\n      add(TibiaPrefsPackage())',
        );
      } else {
        // Java template:  new PackageList(this).getPackages()
        src = src.replace(
          /new PackageList\(this\)\.getPackages\(\)/,
          'new PackageList(this).getPackages(); packages.add(new TibiaPrefsPackage())',
        );
      }
    }

    cfg.modResults.contents = src;
    return cfg;
  });
}

// ---------------------------------------------------------------------------
// Compose all steps
// ---------------------------------------------------------------------------

const withAndroidWidget = (config) => {
  config = withWidgetFiles(config);
  config = withWidgetManifest(config);
  config = withWidgetMainApplication(config);
  return config;
};

module.exports = withAndroidWidget;
