/**
 * withAndroidWidget.js — Expo Config Plugin
 *
 * Injects all three TibiaOT home-screen widgets into the Android native
 * project generated by `expo prebuild`. All source files live under
 * mobile/plugins/ so they survive the `--clean` flag used in build-android.sh.
 *
 * Widgets registered:
 *  1. TibiaWidgetProvider    — 4×1 compact (status + CPU/RAM/DISK text)
 *  2. TibiaBarWidgetProvider — 4×2 horizontal-bar style (CPU/RAM/DISK/PING bars)
 *  3. TibiaArcWidgetProvider — 4×2 circular-arc style  (CPU/RAM/DISK/PING arcs)
 *
 * What this plugin does:
 *  1. Copies Java sources  → android/app/src/main/java/…/widget/
 *  2. Copies XML resources → android/app/src/main/res/{layout,xml,drawable}/
 *  3. Registers all three AppWidgetProvider receivers in AndroidManifest.xml
 *
 * NO native module / NO MainApplication.kt patching required.
 * Each widget reads backendUrl + sessionId directly from AsyncStorage's SQLite
 * database — AppContext.js writes the values there on every connect/disconnect.
 */

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const path = require('path');
const fs   = require('fs');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function copyFile(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

// ---------------------------------------------------------------------------
// Step 1 – copy Java sources + XML resources into the generated android/ dir
// ---------------------------------------------------------------------------

function withWidgetFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const pluginsDir  = path.join(cfg.modRequest.projectRoot, 'plugins');
      const javaDest    = path.join(
        androidRoot,
        'app/src/main/java/com/tibiaotmonitor/widget',
      );
      const resDest     = path.join(androidRoot, 'app/src/main/res');

      // ── Java providers ──────────────────────────────────────────────────
      const javaFiles = [
        'TibiaWidgetProvider.java',
        'TibiaBarWidgetProvider.java',
        'TibiaArcWidgetProvider.java',
      ];
      for (const f of javaFiles) {
        copyFile(
          path.join(pluginsDir, 'java', f),
          path.join(javaDest,           f),
        );
      }

      // ── Layouts ─────────────────────────────────────────────────────────
      const layouts = [
        'tibia_widget_layout.xml',
        'tibia_bar_widget_layout.xml',
        'tibia_arc_widget_layout.xml',
      ];
      for (const f of layouts) {
        copyFile(
          path.join(pluginsDir, 'res/layout', f),
          path.join(resDest,    'layout',     f),
        );
      }

      // ── Widget provider info XMLs ────────────────────────────────────────
      const xmls = [
        'tibia_widget_info.xml',
        'tibia_bar_widget_info.xml',
        'tibia_arc_widget_info.xml',
      ];
      for (const f of xmls) {
        copyFile(
          path.join(pluginsDir, 'res/xml', f),
          path.join(resDest,    'xml',     f),
        );
      }

      // ── Drawables ────────────────────────────────────────────────────────
      const drawables = [
        'widget_bg.xml',
        'ring_progress.xml',
      ];
      for (const f of drawables) {
        copyFile(
          path.join(pluginsDir, 'res/drawable', f),
          path.join(resDest,    'drawable',     f),
        );
      }

      return cfg;
    },
  ]);
}

// ---------------------------------------------------------------------------
// Step 2 – register all three AppWidgetProvider receivers in AndroidManifest
// ---------------------------------------------------------------------------

const RECEIVERS = [
  {
    name:      'com.tibiaotmonitor.widget.TibiaWidgetProvider',
    actions:   ['android.appwidget.action.APPWIDGET_UPDATE',
                'com.tibiaotmonitor.WIDGET_REFRESH'],
    resource:  '@xml/tibia_widget_info',
  },
  {
    name:      'com.tibiaotmonitor.widget.TibiaBarWidgetProvider',
    actions:   ['android.appwidget.action.APPWIDGET_UPDATE',
                'com.tibiaotmonitor.BAR_WIDGET_REFRESH'],
    resource:  '@xml/tibia_bar_widget_info',
  },
  {
    name:      'com.tibiaotmonitor.widget.TibiaArcWidgetProvider',
    actions:   ['android.appwidget.action.APPWIDGET_UPDATE',
                'com.tibiaotmonitor.ARC_WIDGET_REFRESH'],
    resource:  '@xml/tibia_arc_widget_info',
  },
];

function withWidgetManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application[0];
    if (!application.receiver) application.receiver = [];

    for (const r of RECEIVERS) {
      const alreadyRegistered = application.receiver.some(
        (rec) => rec.$['android:name'] === r.name,
      );
      if (alreadyRegistered) continue;

      application.receiver.push({
        $: {
          'android:name':     r.name,
          'android:exported': 'true',
        },
        'intent-filter': [
          {
            action: r.actions.map((a) => ({ $: { 'android:name': a } })),
          },
        ],
        'meta-data': [
          {
            $: {
              'android:name':     'android.appwidget.provider',
              'android:resource': r.resource,
            },
          },
        ],
      });
    }

    return cfg;
  });
}

// ---------------------------------------------------------------------------
// Compose
// ---------------------------------------------------------------------------

const withAndroidWidget = (config) => {
  config = withWidgetFiles(config);
  config = withWidgetManifest(config);
  return config;
};

module.exports = withAndroidWidget;
