/**
 * withAndroidWidget.js — Expo Config Plugin
 *
 * Injects the TibiaOT home-screen widget into the Android native project
 * generated by `expo prebuild`.  All source files live under mobile/plugins/
 * so they survive the `--clean` flag used in build-android.sh.
 *
 * What this plugin does:
 *  1. Copies Java sources  → android/app/src/main/java/com/tibiaotmonitor/widget/
 *  2. Copies XML resources → android/app/src/main/res/{layout,xml,drawable}/
 *  3. Registers the AppWidgetProvider receiver in AndroidManifest.xml
 *  4. Registers TibiaPrefsPackage in MainApplication.kt (or .java)
 *
 * NOTE: Step 4 uses withDangerousMod (runs last, after all other mods) so
 * that MainApplication.kt already exists when we patch it.  Plain string
 * replacement is used instead of regex to avoid silent mismatches.
 */

const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const path = require('path');
const fs   = require('fs');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function copyFile(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

// ---------------------------------------------------------------------------
// Step 1 – copy Java sources + XML resources into the generated android/ dir
// (runs as a dangerous mod so it is ordered with Step 3 below)
// ---------------------------------------------------------------------------

function withWidgetFiles(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const pluginsDir  = path.join(cfg.modRequest.projectRoot, 'plugins');

      // Java sources
      const javaDest = path.join(
        androidRoot,
        'app/src/main/java/com/tibiaotmonitor/widget',
      );
      for (const file of [
        'TibiaWidgetProvider.java',
        'TibiaPrefsModule.java',
        'TibiaPrefsPackage.java',
      ]) {
        copyFile(
          path.join(pluginsDir, 'java', file),
          path.join(javaDest, file),
        );
      }

      // XML resources
      copyFile(
        path.join(pluginsDir, 'res/layout/tibia_widget_layout.xml'),
        path.join(androidRoot, 'app/src/main/res/layout/tibia_widget_layout.xml'),
      );
      copyFile(
        path.join(pluginsDir, 'res/xml/tibia_widget_info.xml'),
        path.join(androidRoot, 'app/src/main/res/xml/tibia_widget_info.xml'),
      );
      copyFile(
        path.join(pluginsDir, 'res/drawable/widget_bg.xml'),
        path.join(androidRoot, 'app/src/main/res/drawable/widget_bg.xml'),
      );

      return cfg;
    },
  ]);
}

// ---------------------------------------------------------------------------
// Step 2 – register the AppWidgetProvider receiver in AndroidManifest.xml
// ---------------------------------------------------------------------------

function withWidgetManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application[0];

    if (!application.receiver) application.receiver = [];

    // Avoid duplicate entries on repeated prebuild runs
    const alreadyRegistered = application.receiver.some(
      (r) =>
        r.$['android:name'] === 'com.tibiaotmonitor.widget.TibiaWidgetProvider',
    );
    if (alreadyRegistered) return cfg;

    application.receiver.push({
      $: {
        'android:name':     'com.tibiaotmonitor.widget.TibiaWidgetProvider',
        'android:exported': 'true',
      },
      'intent-filter': [
        {
          action: [
            { $: { 'android:name': 'android.appwidget.action.APPWIDGET_UPDATE' } },
          ],
        },
      ],
      'meta-data': [
        {
          $: {
            'android:name':     'android.appwidget.provider',
            'android:resource': '@xml/tibia_widget_info',
          },
        },
      ],
    });

    return cfg;
  });
}

// ---------------------------------------------------------------------------
// Step 3 – register TibiaPrefsPackage in MainApplication.kt / .java
//
// withDangerousMod runs AFTER all other mods, so MainApplication.kt is
// already written by the time this callback executes.
// Plain string matching is used (no regex) so whitespace/indentation
// differences can never cause a silent skip.
// ---------------------------------------------------------------------------

function withWidgetMainApplication(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const pkgDir = path.join(
        androidRoot,
        'app/src/main/java/com/tibiaotmonitor',
      );

      // Expo 51 generates Kotlin; older setups may use Java
      const ktPath   = path.join(pkgDir, 'MainApplication.kt');
      const javaPath = path.join(pkgDir, 'MainApplication.java');
      const filePath = fs.existsSync(ktPath)
        ? ktPath
        : fs.existsSync(javaPath) ? javaPath : null;

      if (!filePath) {
        console.warn(
          '[withAndroidWidget] MainApplication not found — TibiaPrefsPackage not registered',
        );
        return cfg;
      }

      const isKotlin = filePath.endsWith('.kt');
      let src = fs.readFileSync(filePath, 'utf8');

      // ── 1. Add import ────────────────────────────────────────────────────
      const importLine = 'import com.tibiaotmonitor.widget.TibiaPrefsPackage';
      if (!src.includes(importLine)) {
        // Anchor: PackageList import is always present in Expo-generated files
        const anchor = 'import com.facebook.react.PackageList';
        if (src.includes(anchor)) {
          src = src.replace(anchor, `${importLine}\n${anchor}`);
        } else {
          // Fallback: insert right after the package declaration
          src = src.replace(
            'package com.tibiaotmonitor',
            `package com.tibiaotmonitor\n\n${importLine}`,
          );
        }
      }

      // ── 2. Register the package ──────────────────────────────────────────
      if (!src.includes('TibiaPrefsPackage()')) {
        if (isKotlin) {
          // Expo 51 template: "PackageList(this).packages.apply {"
          const anchor = 'PackageList(this).packages.apply {';
          if (src.includes(anchor)) {
            src = src.replace(
              anchor,
              `${anchor}\n          add(TibiaPrefsPackage())`,
            );
          } else {
            console.warn(
              '[withAndroidWidget] Could not find PackageList anchor in MainApplication.kt',
            );
          }
        } else {
          // Java template
          const anchor = 'new PackageList(this).getPackages()';
          if (src.includes(anchor)) {
            src = src.replace(
              anchor,
              `new PackageList(this).getPackages(); packages.add(new TibiaPrefsPackage())`,
            );
          }
        }
      }

      fs.writeFileSync(filePath, src);
      return cfg;
    },
  ]);
}

// ---------------------------------------------------------------------------
// Compose all steps
// ---------------------------------------------------------------------------

const withAndroidWidget = (config) => {
  config = withWidgetFiles(config);
  config = withWidgetManifest(config);
  config = withWidgetMainApplication(config);
  return config;
};

module.exports = withAndroidWidget;
